[package]
name = "rust_1brc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
num_cpus = "1.16.0"
threadpool = "1.8.1"

